import './globals.css'
import type { Metadata } from 'next'
import { Inter, Saira_Stencil_One, Instrument_Sans} from 'next/font/google'

const inter = Inter({ subsets: ['latin'],
  variable: '--font-inter'
})
const sairaStencilOne = Saira_Stencil_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-saira-stencil-one'
})

const instrument_Sans = Instrument_Sans({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-instrument-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sairaStencilOne.variable} ${instrument_Sans.variable}` }>{children}</body>
    </html>
  )
}
